'use strict';

let loca=['Seattle','Tokyo','Dubai','Paris','Lima'];
let divElement=document.getElementById('salesPage');
console.log(divElement);

let aElement=document.createElement('a');
divElement.appendChild(aElement);
aElement.textContent='back to home';
aElement.href='./index.html';

//---------------------------(seattle location)------------------------------------
const Seattle={
  minNumberOfCustumor:23, // min number of customer (fixed)
  maxNumberOfCustumor:65,// max number of customer (fixed)
  avg:6.3,// avg number of customer (fixed)
  customerNumbre:0, // number auto-generated by random function.


  time:['6am','7am','8am','9am','10am','11am','12am','1pm','2pm','3pm','4pm','5pm','6pm','7pm','total'], //time array
  total:0, // total number of cookies
  cookieNumber:[],// cookie ammount per hour


  //method to get a random number of the customer
  getNumberOfCustumer: function(min,max){

    this.customerNumbre=Math.floor(Math.random() * (max - min + 1) + min);
    return this.customerNumbre;
  },

  //method to get a number of cookies depend on number of customer*avg
  randomCookiesNumber: function()
  {
    for(let i=0 ; i<this.time.length ; i++){
      this.cookieNumber[i]=Math.floor(this.customerNumbre*this.avg);
      this.total=this.total+this.cookieNumber[i];
      this.getNumberOfCustumer(this.minNumberOfCustumor,this.maxNumberOfCustumor);
    }
    this.cookieNumber[this.time.length-1]=this.total;
    return this.cookieNumber;
  },

  // method to deal with html elements
  render:function(){

    let h2Element=document.createElement('h2');
    divElement.appendChild(h2Element);
    h2Element.textContent='here is the stock inside inventory in Seattle ';

    //for(let i=0; i<loca.length; i++)

    let h4Element=document.createElement('h4');
    divElement.appendChild(h4Element);
    h4Element.textContent= loca[0];

    let ulElement=document.createElement('ul');
    h4Element.appendChild(ulElement);

    for(let i=0; i<this.time.length; i++)
    {
      let liElement= document.createElement('li');
      ulElement.appendChild(liElement);
      liElement.textContent= this.time[i] +' : '+this.cookieNumber[i];
    }
  }

};
//----------------------------------(tokyo location)--------------------------------------

const Tokyo={
  minNumberOfCustumor:3, // min number of customer (fixed)
  maxNumberOfCustumor:24,// max number of customer (fixed)
  avg:1.2,// avg number of customer (fixed)
  customerNumbre:0, // number auto-generated by random function.


  time:['6am','7am','8am','9am','10am','11am','12am','1pm','2pm','3pm','4pm','5pm','6pm','7pm','total'], //time array
  total:0, // total number of cookies
  cookieNumber:[],// cookie ammount per hour


  //method to get a random number of the customer
  getNumberOfCustumer: function(min,max){

    this.customerNumbre=Math.floor(Math.random() * (max - min + 1) + min);
    return this.customerNumbre;
  },

  //method to get a number of cookies depend on number of customer*avg
  randomCookiesNumber: function()
  {
    for(let i=0 ; i<this.time.length ; i++){
      this.cookieNumber[i]=Math.floor(this.customerNumbre*this.avg);
      this.total=this.total+this.cookieNumber[i];
      this.getNumberOfCustumer(this.minNumberOfCustumor,this.maxNumberOfCustumor);
    }
    this.cookieNumber[this.time.length-1]=this.total;
    return this.cookieNumber;
  },

  // method to deal with html elements
  render:function(){

    let h2Element=document.createElement('h2');
    divElement.appendChild(h2Element);
    h2Element.textContent='here is the stock inside inventory in Tokyo ';

    let h4Element=document.createElement('h4');
    divElement.appendChild(h4Element);
    h4Element.textContent= loca[1];

    let ulElement=document.createElement('ul');
    h4Element.appendChild(ulElement);

    for(let i=0; i<this.time.length; i++)
    {
      let liElement= document.createElement('li');
      ulElement.appendChild(liElement);
      liElement.textContent= this.time[i] +' : '+this.cookieNumber[i];
    }
  }

};

//----------------------(dubai location)---------------------------
const Dubai={
  minNumberOfCustumor:11, // min number of customer (fixed)
  maxNumberOfCustumor:38,// max number of customer (fixed)
  avg:3.7,// avg number of customer (fixed)
  customerNumbre:0, // number auto-generated by random function.


  time:['6am','7am','8am','9am','10am','11am','12am','1pm','2pm','3pm','4pm','5pm','6pm','7pm','total'], //time array
  total:0, // total number of cookies
  cookieNumber:[],// cookie ammount per hour


  //method to get a random number of the customer
  getNumberOfCustumer: function(min,max){

    this.customerNumbre=Math.floor(Math.random() * (max - min + 1) + min);
    return this.customerNumbre;
  },

  //method to get a number of cookies depend on number of customer*avg
  randomCookiesNumber: function()
  {
    for(let i=0 ; i<this.time.length ; i++){
      this.cookieNumber[i]=Math.floor(this.customerNumbre*this.avg);
      this.total=this.total+this.cookieNumber[i];
      this.getNumberOfCustumer(this.minNumberOfCustumor,this.maxNumberOfCustumor);
    }
    this.cookieNumber[this.time.length-1]=this.total;
    return this.cookieNumber;
  },

  // method to deal with html elements
  render:function(){

    let h2Element=document.createElement('h2');
    divElement.appendChild(h2Element);
    h2Element.textContent='here is the stock inside inventory in Dubai ';

    let h4Element=document.createElement('h4');
    divElement.appendChild(h4Element);
    h4Element.textContent= loca[2];

    let ulElement=document.createElement('ul');
    h4Element.appendChild(ulElement);

    for(let i=0; i<this.time.length; i++)
    {
      let liElement= document.createElement('li');
      ulElement.appendChild(liElement);
      liElement.textContent= this.time[i] +' : '+this.cookieNumber[i];
    }
  }

};

//----------------------(paris location)---------------------------
const Paris={
  minNumberOfCustumor:20, // min number of customer (fixed)
  maxNumberOfCustumor:38,// max number of customer (fixed)
  avg:2.3,// avg number of customer (fixed)
  customerNumbre:0, // number auto-generated by random function.


  time:['6am','7am','8am','9am','10am','11am','12am','1pm','2pm','3pm','4pm','5pm','6pm','7pm','total'], //time array
  total:0, // total number of cookies
  cookieNumber:[],// cookie ammount per hour


  //method to get a random number of the customer
  getNumberOfCustumer: function(min,max){

    this.customerNumbre=Math.floor(Math.random() * (max - min + 1) + min);
    return this.customerNumbre;
  },

  //method to get a number of cookies depend on number of customer*avg
  randomCookiesNumber: function()
  {
    for(let i=0 ; i<this.time.length ; i++){
      this.cookieNumber[i]=Math.floor(this.customerNumbre*this.avg);
      this.total=this.total+this.cookieNumber[i];
      this.getNumberOfCustumer(this.minNumberOfCustumor,this.maxNumberOfCustumor);
    }
    this.cookieNumber[this.time.length-1]=this.total;
    return this.cookieNumber;
  },

  // method to deal with html elements
  render:function(){

    let h2Element=document.createElement('h2');
    divElement.appendChild(h2Element);
    h2Element.textContent='here is the stock inside inventory in Paris ';

    let h4Element=document.createElement('h4');
    divElement.appendChild(h4Element);
    h4Element.textContent= loca[3];

    let ulElement=document.createElement('ul');
    h4Element.appendChild(ulElement);

    for(let i=0; i<this.time.length; i++)
    {
      let liElement= document.createElement('li');
      ulElement.appendChild(liElement);
      liElement.textContent= this.time[i] +' : '+this.cookieNumber[i];
    }
  }

};


//----------------------(lima location)---------------------------
const Lima={
  minNumberOfCustumor:2, // min number of customer (fixed)
  maxNumberOfCustumor:16,// max number of customer (fixed)
  avg:4.6,// avg number of customer (fixed)
  customerNumbre:0, // number auto-generated by random function.


  time:['6am','7am','8am','9am','10am','11am','12am','1pm','2pm','3pm','4pm','5pm','6pm','7pm','total'], //time array
  total:0, // total number of cookies
  cookieNumber:[],// cookie ammount per hour


  //method to get a random number of the customer
  getNumberOfCustumer: function(min,max){

    this.customerNumbre=Math.floor(Math.random() * (max - min + 1) + min);
    return this.customerNumbre;
  },

  //method to get a number of cookies depend on number of customer*avg
  randomCookiesNumber: function()
  {
    for(let i=0 ; i<this.time.length ; i++){
      this.cookieNumber[i]=Math.floor(this.customerNumbre*this.avg);
      this.total=this.total+this.cookieNumber[i];
      this.getNumberOfCustumer(this.minNumberOfCustumor,this.maxNumberOfCustumor);
    }
    this.cookieNumber[this.time.length-1]=this.total;
    return this.cookieNumber;
  },

  // method to deal with html elements
  render:function(){

    let h2Element=document.createElement('h2');
    divElement.appendChild(h2Element);
    h2Element.textContent='here is the stock inside inventory in Lima ';

    let h4Element=document.createElement('h4');
    divElement.appendChild(h4Element);
    h4Element.textContent= loca[4];

    let ulElement=document.createElement('ul');
    h4Element.appendChild(ulElement);

    for(let i=0; i<this.time.length; i++)
    {
      let liElement= document.createElement('li');
      ulElement.appendChild(liElement);
      liElement.textContent= this.time[i] +' : '+this.cookieNumber[i];
    }

  }

};



// for seattle location
Seattle.getNumberOfCustumer(Seattle.minNumberOfCustumor,Seattle.maxNumberOfCustumor);
Seattle.randomCookiesNumber();
Seattle.render();

// for tokyo location
Tokyo.getNumberOfCustumer(Tokyo.minNumberOfCustumor,Tokyo.maxNumberOfCustumor);
Tokyo.randomCookiesNumber();
Tokyo.render();

// for dubai location
Dubai.getNumberOfCustumer(Dubai.minNumberOfCustumor,Dubai.maxNumberOfCustumor);
Dubai.randomCookiesNumber();
Dubai.render();

// for paris location
Paris.getNumberOfCustumer(Paris.minNumberOfCustumor,Paris.maxNumberOfCustumor);
Paris.randomCookiesNumber();
Paris.render();

// for lima location
Lima.getNumberOfCustumer(Lima.minNumberOfCustumor,Lima.maxNumberOfCustumor);
Lima.randomCookiesNumber();
Lima.render();
