'use strict';

let time=['6am','7am','8am','9am','10am','11am','12am','1pm','2pm','3pm','4pm','5pm','6pm','7pm','total']; //time array
let divElement=document.getElementById('salesPage');
console.log(divElement);

let aElement=document.createElement('a');
divElement.appendChild(aElement);
aElement.textContent='back to home';
aElement.href='./index.html';

const Seattle =new Locations(23,65,6.3);
const Tokyo = new Locations(3,24,1.2);
const Dubai = new Locations(11,38,3.7);
const Paris = new Locations(20,38,2.3);
const Lima = new Locations(2,16,4.6);

let loca=[Seattle,Tokyo,Dubai,Paris,Lima];
let locationName=['Seattle','Tokyo','Dubai','Paris','Lima'];

//---------------------------(location constructor)------------------------------------

function Locations(minNumberOfCustumor,maxNumberOfCustumor,avg)
{ this.minNumberOfCustumor=minNumberOfCustumor;
  this.maxNumberOfCustumor=maxNumberOfCustumor;
  this.avg=avg;
  this.customerNumbre=0; // number auto-generated by random function.
  this.locationTotal=0;
  this.cookieNumber=[];// cookie ammount per hour

}

Locations.prototype.getNumberOfCustumer= function(min,max){

  this.customerNumbre=Math.floor(Math.random() * (max - min + 1) + min);
  return this.customerNumbre;
};

Locations.prototype.randomCookiesNumber= function()
{
  
  for(let i=0 ; i<time.length ; i++){
    this.cookieNumber[i]=Math.floor(this.customerNumbre*this.avg);
    this.locationTotal=this.locationTotal+this.cookieNumber[i];
    this.getNumberOfCustumer(this.minNumberOfCustumor,this.maxNumberOfCustumor);
  }
  this.cookieNumber[time.length-1]=this.locationTotal;
  return this.cookieNumber;
};


//------------------------------------------------
Locations.prototype.render=function(){

  let tableElement = document.createElement('table');
  divElement.appendChild(tableElement);

  let tr=document.createElement('tr');
  tableElement.appendChild(tr);

  let th1=document.createElement('th');
  th1.textContent=' ';
  tr.appendChild(th1);
  for(let j=0; j<time.length;j++){
    let th2 =document.createElement('th');
    th2.textContent=time[j];
    tr.appendChild(th2);
  }



  for (let i=0;i<locationName.length;i++)
  {
    let tr1=document.createElement('tr'); // number of row
    tableElement.appendChild(tr1);


    let td=document.createElement('td'); //content of row location name
    td.textContent=locationName[i];
    tr1.appendChild(td);

    for(let j=0;j<time.length;j++){
      let td1=document.createElement('td');
      td1.textContent=loca[i].cookieNumber[j];
      tr1.appendChild(td1);
      console.log(loca[i]);
    console.log('value of i= '+i+'value of j= '+j);}
      
  }


  //-----------------------









};




Seattle.getNumberOfCustumer(23,65);
Seattle.randomCookiesNumber();
Seattle.render();

Tokyo.getNumberOfCustumer(3,24);
Tokyo.randomCookiesNumber();
Tokyo.render();

Paris.getNumberOfCustumer(20,38);
Paris.randomCookiesNumber();
Paris.render();
 
Dubai.getNumberOfCustumer(11,38);
Dubai.randomCookiesNumber();
Dubai.render();

Lima.getNumberOfCustumer(2,16);
Lima.randomCookiesNumber();
Lima.render();
